name: auraflow
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  build_runner: ^2.4.13
  flutter:
    sdk: flutter
  flutter_colorpicker: ^1.1.0
  flutter_markdown: ^0.7.7+1
  flutter_staggered_animations: ^1.1.1
  flutter_staggered_grid_view: ^0.7.0
  google_fonts: ^6.3.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.20.2
  provider: ^6.1.5
  responsive_builder: ^0.7.1
  shared_preferences: ^2.5.3
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
flutter_launcher_icons:

  adaptive_icon_background: "#ffffff" 
  adaptive_icon_foreground: "assets/applogo/logo.png" 

  ios: true
  android: true 
  windows:
    generate: true 
    icon_size: 256
  image_path: "assets/applogo/logo.png" 
  min_sdk_android: 21
  remove_alpha_ios: true
